### PR TITLE
Fixtests

### PR DESCRIPTION
**Pull request by wnichols1**
whilst I haven't finished these tests, I think they are better than they were.

### CODE REVIEW

**Review by ajgdls — APPROVED** [review]

**Comment by ajgdls** [comment]
Looks better.  Could the final test failing on travis be cleaned up to give a green tick?

**Comment by wnichols1** [comment]
That last one percival.detector.test_percivalDetector.TestPercivalDetector was too difficult for me to fix in a day, so I decided to postpone it.

**Comment by wnichols1** [comment]
I've skipped percival.detector.test_percivalDetector.TestPercivalDetector.
Have I made a mess of the code by adding const. sporadically? I don't want to do that.

**Comment by ajgdls** [comment]
Well it might be a good idea to search through the code and make sure you are consistent, ensuring all instances now have the word const if you want to add it.  I could see one case where in the same line you used it for once instance and not another.

You have fixed the tests though and now Travis is passing.

**Comment by wnichols1** [comment]
ok well I've reverted some of those const things.

I think this can go in now. Shall I squash stuff? Note that detector.py has changed.

**Pull request merged**
