### PR TITLE
add new scripts for wiener control

### PR DESCRIPTION
**Pull request by wnichols1**
I have replaced the old scripts that controlled power to the powerboard because
*) if a supervisor level is breached on the wiener, it just switches the channel off
*) this is dangerous for us, and the old scripts did not set supervisor levels
*) I have effectively disabled the supervisor levels by setting wide tolerances
*) currentLimit and outputVoltage still work as we expect, and they the important things
*) I have used the wiener voltage-ramping facility to ramp the voltages at 1 or 2 v/sec

Please check that I have set the correct voltages and currentLimits for each channel!

thanks
will.

### CODE REVIEW

**Comment by wnichols1** [comment]
a good question to ask is whether I am sending the commands in the right order. Is it better to group them differently?

**Comment by wnichols1** [comment]
yes, I could use argparse.
yes, I prob will make the ip address an option.
the bash scripts are different. Yes, the plan is to run the bash script and then verify.

My overall consideration is to keep these scripts readable and simple, because there are lots of people on the Percival Project who are not software gurus, and so I have not done any clever stuff which I probably would do if it was my own project.

**Comment by wnichols1** [comment]
i have used argparse and added an option for wiener address

**Comment by ajgdls** [comment]
:+1:

**Pull request merged**
