### PR TITLE
Shorten scan setpoints

### PR DESCRIPTION
**Pull request by wnichols1**
this alters what scan-setpoints does, and also setting num stages to 2, and dwell time to 500.

### CODE REVIEW

**Comment by wnichols1** [comment]
There are some tidying commits at the start of this, before the two commits which alter things.

**Comment by prcvlusr** [comment]
A) regarding rename odin config files: it is OK
B) regarding set num scan-stages to 2, and dwell to 500ms. Add apply-setpoints.:
1) I do not have problem with changing the ramp from 4 steps, 2s to 2 steps, 0.5sec
2) but please do not change:
-  DESY/W3C3/user_scripts/TEST_BEFORE_POWERUP.sh 
-  DESY/W3C3/user_scripts/TEST_slow_POWERUP_000_onlyVDDs.sh 
these are debugging scripts.
3) regarding minimize the action of scan_set_points
it is important that we retain a version of the scan_set_points command that acts as it used to do (i.e. it applies all the setting from the start).
It does not need to have the same command name, but we need to be able, in any point, to apply a scan_set_points-as it was-before.
this is required for debugging or emergency actions (e.g. a ramp fails and you end in the middle of two stages)
I do not understand from the code how can we achieve this.

**Comment by wnichols1** [comment]
I think the command you are looking for is percival-hl-apply-setpoint.
and you will see things like this in the new scripts:
percival-hl-apply-setpoint -s 00_0_0V0A

I will revert (2)

**Comment by wnichols1** [comment]
I am going to suggest that we delete these scripts in (2) from github because I think
i) they are easily recreated, being mostly copies of other things
ii) they are not generally useful and I doubt anyone will use them except Alessandro
iii) It's unclear what they are meant to do

is that ok?

**Comment by wnichols1** [comment]
closed accidentally; reopening!

**Review by prcvlusr — APPROVED** [review]

**Comment by wnichols1** [comment]
I think there is a difference between MERGING a branch and APPROVING a branch.
I wanted approval from agreer before merging, but he can do this retrospectively.

**Comment by ajgdls** [comment]
I don't think I can approve it now by clicking an any buttons, so you can consider this comment as my approval @wnichols1

**Pull request merged**
