### PR TITLE
DESY system at 2020.02.25

### PR DESCRIPTION
**Pull request by prcvlusr**
status of the DESY system (cfeld-percival01) at 2020.02.25.
pull requested to make available to the other partners
- the scripts in percivalui/DESY/W3C3/user_script (used for chip powerUp/Down and similar)
- the ini files and biases xls in percivalui/DESY/W3C3/config (used by scripts above)
- the python and .sh files in percivalui/sandbox (used for acquisitions)

### CODE REVIEW

**Comment by wnichols1** [comment]
run git diff master --name-status to see a list of files.
All the files are text files except for
DESY/W3C3/config/05_Spreadsheets/DESY_W3C3_Setpoint_Definitions.xls
which we must be careful about.
Only seven files have been modified; the other 150 are NEW FILES.

**Comment by prcvlusr** [comment]
> I have deleted all the unacceptable files: logs, Debug,
there are some (actually many) file that have Debug as part of in their name and/or their folder name that are actually essential for operation.
this includes for example:  everything in percival/percivalui/DESY/W3C3/config/04_Sensor_Settings/
SensorDebug_0xx_SET_CPNI_nd_dmxSEL.ini, SensorDebug_000_SAFE_START.ini, SensorDebug_0xx_SET_dmxSEL.ini

**Comment by wnichols1** [comment]
ok well perhaps we can rename these "debug" files, I have put them back in.

**Comment by wnichols1** [comment]
Can we get this approved an in tmw morning please as I don't want to be waiting around any more.

**Comment by wnichols1** [comment]
right lets get that in then, I've added carrier board firmware to config; altho I don't know how useful that is.

**Pull request merged**
