### PR TITLE
Fix null msgs

### PR DESCRIPTION
**Pull request by wnichols1**
this must be checked very carefully because it could break a sensor
Please look at each commit individually

### CODE REVIEW

**Comment by ajgdls** [comment]
Can this be re-based after PR #125 has been merged so that it only contains the single commit relevant to this PR.

**Comment by wnichols1** [comment]
yes

**Comment by wnichols1** [comment]
I think this one can be closed as it's gone in elsewhere

**Comment by ajgdls** [comment]
Can this now be closed?

**Comment by wnichols1** [comment]
I think there is still an important change here. I've rebased it and I think we want to consider it carefully.

**Pull request closed without merging**
