### PR TITLE
rewrite button gui for percival operation

### PR DESCRIPTION
**Pull request by wnichols1**
this is a major overhaul of the percival gui. The config is now easy to read as a dict in server.py, and you can have actions after reaching level n. The enable / disable of the buttons is now set in the server instead of the buttons. I can't see this transporting to http or epics because it has become too complex.

### CODE REVIEW

**Comment by wnichols1** [comment]
Don't spend much time reviewing it, but just a quick glance might be helpful.

**Review by ajgdls — APPROVED** [review]
The only real question I have is why all of the ';' at the end of each line?

**Comment by wnichols1** [comment]
> The only real question I have is why all of the ';' at the end of each line?

convention and habit. And the question is also why not?

**Comment by wnichols1** [comment]
close this because it's done elsewhere

**Pull request closed without merging**
